config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      put :downvote, action: 'downvote'
      put :upvote, action: 'upvote'
    end
  end

  concern :favoritable do
    member do
      put :toggle_like, action: 'toggle_like'
    end
  end

  concern :commentable do
    resources :comments, only: [:index, :create]
  end

  devise_for :cenobites, skip: :invitations, controllers: {
    sessions: 'sessions/sessions',
  }

  devise_scope :cenobite do
    # Disable every invitation route except "/accept", we're managing these in
    # acquaintances
    get 'cenobites/invitations/accept', to: 'devise/invitations#edit', as: :accept_cenobite_invitation
    put 'cenobites/invitations', to: 'devise/invitations#update', as: :cenobite_invitation
  end

  root to: 'hellcome#index'

  resources :links, only: [:index]
  resources :pastes, only: [:show] do
    member do
      match :reveal, to: 'pastes#reveal', via: [:put, :patch, :get]
    end
  end

  namespace :member do
    resources :acquaintances, only: [:index, :new, :create, :destroy] do
      member do
        post :accept
        put :resend_request
      end
    end
    resources :cenobites, only: [:index] do
      member do
        post :invite
      end
    end
    get :chat, to: 'chat#index', as: :chat
    resources :chat_rooms, except: [:new, :edit] do
      resources :chat_messages, except: [:new, :edit]
      resources :chat_presences, only: [:index]
    end
    resources :chat_participants, except: [:new, :create, :edit]
    resources :comments, except: [:index, :new, :create, :edit]
    resources :dead_man_switches, constraints: { id: /\d+/ } do
      member do
        put :ping
        put :rearm
      end
      collection do
        put :ping_all
      end
    end
    resources :events, concerns: [:commentable] do
      member do
        put :attend
        delete :leave
      end
    end
    resources :fortunes, except: [:show], concerns: :votable do
      collection do
        get :random
      end
    end
    resources :invites, only: [:destroy] do
      member do
        put :resend
      end
    end
    resources :items do
      collection do
        post :bulk_create
      end
    end
    resources :likes, only: [:index, :destroy]
    resources :links, except: [:index, :show], concerns: [:votable, :favoritable]
    resources :motions, concerns: [:votable, :commentable] do
      member do
        post :subscribe
        post :unsubscribe
      end
    end
    resources :page, only: [:show]
    resources :pastes
    resource :preferences, controller: :cenobites, only: [:edit, :update]
    resources :rss_feeds, except: [:show]
    resources :rss_items, only: [:index], concerns: [:votable, :favoritable]
    get :stats, to: 'stats#show', as: :stats
    resources :subscriptions, only: [:index, :destroy]
  end

  # Styleguide routes
  mount Styleguide::Engine => '/style' unless Rails.env.production?
end

app/controllers/hellcome_controller.rb
class HellcomeController < ApplicationController
  def index; end
end

app/views/hellcome/_item.html.haml
%div
  .element.element--card.element--centered
    %h2.element__title= link
    .element__content= description

app/views/hellcome/_logo.html.haml
:ruby
  logo = {}
  logo[:small] = <<~TEXT
    ╻ ╻┏━╸╻  ╻  ┏━┓┏━┓╻┏━┓┏━╸┏━┓ ╻┏━┓
    ┣━┫┣╸ ┃  ┃  ┣┳┛┣━┫┃┗━┓┣╸ ┣┳┛ ┃┃ ┃
    ╹ ╹┗━╸┗━╸┗━╸╹┗╸╹ ╹╹┗━┛┗━╸╹┗╸╹╹┗━┛
  TEXT

  logo[:medium] = <<~TEXT
    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
    ░░█░█░█▀▀░█░░░█░░░█▀█░█▀█░▀█▀░█▀▀░█▀▀░█▀█░░░░▀█▀░█▀█░░
    ░░█▀█░█▀▀░█░░░█░░░█▀▄░█▀█░░█░░▀▀█░█▀▀░█▀▄░░░░░█░░█░█░░
    ░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░░▀▀▀░▀▀▀░░
    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  TEXT

  logo[:large] = <<~TEXT
    ▄              ▄       ▄                                            ▄              ▄
      ██░ ██▓█████ ██▓    ██▓    ▄█▀███   ███▓  ██▓ █████▓█████ ▄█▀███      ██▓▒█████
     ▓██░ ██▓█   ▀▓██▒   ▓██▒   ▓██ ▒ ██▓██▒ ██▓██▒██    ▓█   ▀▓██ ▒ ██    ▓░░▒██▒  ██
     ▒██▀▀██▒███  ▒██░   ▒██░   ▓██ ░▄█ ▒██▄▄██▒██░ ▓██▄ ▒███  ▓██ ░▄█     ▒██▒██░  ██
     ░▓█ ░██▒▓█  ▄▒██░   ▒██░   ▒██▀▀█▄ ░██▓▒██░██░ ▒   █▒▓█  ▄▒██▀▀█▄     ░██▒██   ██
     ░▓█▒░██░▒████░▀█████░▀█████░▀█▓ ▒██░▓█▒░▓█░██▒██████░▒████░▀█▓ ▒██▒██▓░██░ ████▓▒
       ▒ ░░▒░░░ ▒░ ░ ▒░▓  ░ ▒░▓  ░ ▒▓ ░▒▓▒▓ ░▒▒ ▓ ▒ ▒▓▒ ▒░░ ▒░ ░ ▒▓ ░▒ ░▒▓▒░▓ ░ ▒░▒░▒░
       ▒ ░▒░ ░░ ░  ░ ░ ▒  ░ ░ ▒  ░ ░▒ ░ ▒░▒  ▒░ ▒ ░ ░▒  ░ ░ ░  ░ ░▒ ░  ░░▒  ▒ ░ ░ ▒ ▒░
       ░  ░░ ░  ░    ░ ░    ░ ░    ░░   ░ ░  ░░ ▒ ░  ░  ░   ░    ░░     ░   ▒ ░ ░ ░ ▒
       ░  ░  ░  ░  ░   ░  ░   ░  ░  ░   ░     ░ ░       ░   ░  ░  ░      ░  ░     ░ ░
          ░                   ░               ░                   ░
  TEXT

.text-logo__wrapper
  - [:small, :medium, :large].each do |size|
    %pre.text-logo.text--glitch{ class: "#{size == :large ? '' : 'text-glitch--skew'} text-logo--#{size}",
                                data: { text: logo[size] } }= logo[size]

app/views/hellcome/index.html.haml
- if current_cenobite

  = render 'logo'

  .grid-3
    %div
      %h2= t('.common_services')
      = render 'item',
                link: link_to(t('layouts.application.motions'), member_motions_path),
                description: t('layouts.application.motions_description')
      = render 'item',
                link: link_to(t('layouts.application.chat'), member_chat_path),
                description: t('layouts.application.chat_description')
      = render 'item',
                link: link_to(t('layouts.application.events'), member_events_path),
                description: t('layouts.application.events_description')
      - if policy([:member, Cenobite]).index?
        = render 'item',
                  link: link_to(t('layouts.application.bottin'), member_cenobites_path),
                  description: t('layouts.application.bottin_description')
      - else
        = render 'item',
                  link: t('layouts.application.bottin'),
                  description: t('layouts.application.bottin_inaccessible_description',
                                  link: link_to(t('layouts.application.preferences'),
                                                edit_member_preferences_path)).html_safe
      = render 'item',
                link: link_to(t('activerecord.models.fortune', count: 2), random_member_fortunes_path),
                description: t('layouts.application.fortune_description')
      = render 'item',
                link: link_to(t('layouts.application.links'), links_path),
                description: t('layouts.application.links_description')
      = render 'item',
                link: link_to(t('layouts.application.articles'), member_rss_items_path),
                description: t('layouts.application.articles_description')
      = render 'item',
                link: link_to(t('layouts.application.stats'), member_stats_path),
                description: t('layouts.application.stats_description')
      = render 'item',
                link: link_to(t('layouts.application.changelog'), member_page_path('changelog')),
                description: t('layouts.application.changelog_description')

    %div
      %h2= t('.private_services')
      = render 'item',
                link: link_to(t('layouts.application.dead_man_switches'), member_dead_man_switches_path),
                description: t('layouts.application.dead_man_switches_description')
      = render 'item',
                link: link_to(t('layouts.application.pastes'), member_pastes_path),
                description: t('layouts.application.pastes_description')
      = render 'item',
                link: link_to(t('layouts.application.items'), member_items_path),
                description: t('layouts.application.items_description')
      = render 'item',
               link: link_to(t('layouts.application.favorites'), member_likes_path),
               description: t('layouts.application.favorites_description')

    %div
      %h2= t('.your_menu')
      = render 'item',
                link: link_to(t('layouts.application.acquaintances'), member_acquaintances_path),
                description: t('layouts.application.acquaintances_description')
      = render 'item',
               link: link_to(t('layouts.application.preferences'), edit_member_preferences_path),
               description: t('layouts.application.preferences_description')
      = render 'item',
               link: link_to(t('layouts.application.subscriptions'), member_subscriptions_path),
               description: t('layouts.application.subscriptions_description')

- else
  %center
    .logo-wrapper
      %svg.logo{ xmlns: 'http://www.w3.org/2000/svg', width: 427.336, height: 493.445, viewBox: '0 0 113.066 130.557' }
        %g.cube
          %path{ d: 'M.265 97.765V32.792L56.533.306 112.8 32.792v64.973l-56.268 32.487z' }
          %path{ d: 'M48.513 60.648l8.02 4.63v9.261M64.553 60.648l-8.02 4.63' }